### ISSUE TITLE
Issue on out of order array fields 

### ISSUE THREAD

**Issue by rentzso** [gllmflndn/JSONio#3]
Hi @gllmflndn,
reading a json with an array of objects with differently ordered fields gives this error:
```
>> jsonread(f)
Error using cell2mat (line 63)
The field names of each cell array element must be consistent and in consistent order.
```

An example to reproduce the error is the following:
```
[{
    "foo": "1", "bar": "2"
},
{
    "bar": "1", "foo": "3"
}]
```

**Comment by gllmflndn** [comment]
Hi @rentzso,
Confirmed, thanks. The bug is at this line:
 https://github.com/gllmflndn/JSONio/blob/master/jsonread.c#L89
This checks whether structs can be concatenated if they have the same fieldnames but ignore order.
For compatibility with ``jsondecode``, once fixed, your example will return a cell array:
````
>> jsondecode('[{"foo":1,"bar":2},{"bar":1,"foo":3}]')

ans =

  2×1 cell array

    [1×1 struct]
    [1×1 struct]

>> jsondecode('[{"foo":1,"bar":2},{"foo":1,"bar":3}]')

ans = 

  2×1 struct array with fields:

    foo
    bar
````

**Comment by gllmflndn** [comment]
f7ca24a should fix the issue and have `jsonread` behave like `jsondecode`. So far I have only recompiled the MEX file for 64bit Linux so you would have to do this yourself if you are using another platform.

**Comment by rentzso** [comment]
Thanks @gllmflndn! The fix seems to work (also on MacOS) without recompilation.

**Comment by gllmflndn** [comment]
Thanks for the feedback. I also recompiled the MEX file for macOS in 3ffaace. The remaining platforms are 32 and 64 bit Windows.
