### ISSUE TITLE
Round trip on a JSON file with replacementStyle 'hex'

### ISSUE THREAD

**Issue by wandell** [gllmflndn/JSONio#4]
I just noticed the behavior below.  At first it surprised me.  But with some thought it might be the right behavior.  If so, the perhaps this behavior could be explained in the header of the m-file a bit more.

```
%% Reading a '.' in an input JSON string.
%
% We use the opts argument to put a '.' in the output string.
%
clear srch
srch.subject0x2Eage= 1;    % Indicate we want a '.' in the JSON string
jsonwrite('test.json',srch,struct('replacementStyle','hex'))
type test.json                      % Looks good.

% Read the JSON file with replacement setting. It comes back with an underscore, not
% the hex field.  Hence, the write/read round-trip is not the identity.

test = jsonread('test.json',struct('replacementStyle','hex'));

% The returned struct does not have the hex code, but rather an underscore

test

```

**Comment by gllmflndn** [comment]
Thanks for the feedback; this is a bug with the name of the optional parameter being case sensitive. This will work only if you use:
`test = jsonread('test.json',struct('ReplacementStyle','hex'));`
I have made a change in jsonread.c to not be sensitive to case and will push it soon.

**Comment by wandell** [comment]
Thank you.  And the tool is really great!
