### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by tholu** [gllmflndn/JSONio#5]
The README should contain information about how to get started. If I just use the addpath, I get the following error:

```
error: jsonread.c not compiled.
```

**Comment by tholu** [comment]
Solved by manually running `mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS` (OS X Mojave).

**Comment by gllmflndn** [comment]
Hi @tholu,
Thanks for the feedback; more information about compilation is indeed required. I'll also push a new version of the MEX files that should be more widely compatible.
