### ISSUE TITLE
Errors on Tests with MATLAB R2020a

### ISSUE THREAD

**Issue by RoyiAvital** [gllmflndn/JSONio#6]
I have MATLAB R2020a on Windows 10.

This is what I get when running the tests:

```
>> runtests('test_jsonread')
Running test_jsonread
..
================================================================================
Error occurred in test_jsonread/test_jsonread_all_types and it did not run to completion.
    ---------
    Error ID:
    ---------
    'MATLAB:cell2mat:InconsistentFieldNames'
    --------------
    Error Details:
    --------------
    Error using cell2mat (line 63)
    The field names of each cell array element must be consistent and in consistent order.
    
    Error in test_jsonread>test_jsonread_all_types (line 127)
    act  = jsonread(json);
================================================================================
.
Done test_jsonread
__________

Failure Summary:

     Name                                   Failed  Incomplete  Reason(s)
    ======================================================================
     test_jsonread/test_jsonread_all_types    X         X       Errored.

ans = 

  1×3 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration
    Details

Totals:
   2 Passed, 1 Failed (rerun), 1 Incomplete.
   0.053918 seconds testing time.
```

**Comment by gllmflndn** [comment]
Thank you, the MEX file needs to be recompiled for the Windows platform. I'll do that shortly.

**Comment by gllmflndn** [comment]
I pushed a new version in https://github.com/gllmflndn/JSONio/commit/6c699a315ac2c578864d8b740a061bff47b718bf. Hopefully the tests should now pass successfully.

**Comment by RoyiAvital** [comment]
Indeed it seems to work.

By the way, are you aware of `C` library to generate `JSON` file from structs?

**Comment by gllmflndn** [comment]
This is not something I looked into as I'm not sure how much faster it could be from a M implementation. Do you have particular issues with speed? These are C++ libraries but you can look into the libraries discussed for JSON support in Octave:
https://savannah.gnu.org/bugs/?53100
https://lists.gnu.org/archive/html/octave-maintainers/2020-03/msg00022.html

**Comment by RoyiAvital** [comment]
It is not for doing something form MATLAB, it is to do something equivalent to your function in `C`.
