### ISSUE TITLE
Mex files for Apple Silicon

### ISSUE THREAD

**Issue by gkaguirre** [gllmflndn/JSONio#7]
Could you provide the routine "jsonread" compiled for native Apple Silicon processor (". mexmaca64")?

**Comment by gllmflndn** [comment]
Now added in e6c5b3e. Let me know if you have any issue with it.

**Comment by gkaguirre** [comment]
Thank you!--Geoffrey Karl Aguirre, MD, PhDhttp://gkaguirre.comProfessor of NeurologyUniversity of PennsylvaniaOn Nov 18, 2023, at 11:53 AM, Guillaume Flandin ***@***.***> wrote:﻿
Now added in e6c5b3e. Let me know if you have any issue with it.
